#!/usr/bin/env bun
/**
 * codeowners.ts — generate `.github/CODEOWNERS` from the `author:` of every
 * skill, and fail CI when the committed file differs.
 *
 * Why it exists: until 2026-09-23 anyone with write access could approve a
 * change to anyone's skill. The `pull_request` rule asked for one approval from
 * ANY reviewer, and no file said who owns what. Now the owner of a skill is its
 * `author:` handle, this file turns that into CODEOWNERS, and the repository
 * ruleset requires a code-owner review. Docs: README.md, "Dono e revisão".
 *
 * Who owns what:
 *
 *   - `skills/<slug>/` is owned by the `author:` in its SKILL.md frontmatter
 *     (top-level, or under `metadata:` — the same value ingest publishes).
 *   - No `author:`, or `author: devfellowship`, means the core team owns it.
 *   - Every owned line also names core, so an owner who loses write access
 *     never leaves a path with NO owner, which GitHub would read as "no
 *     code-owner review needed".
 *   - Everything else falls to core via `*`, including a NEW skill: GitHub
 *     reads CODEOWNERS from the TARGET branch, so a new path has no line yet.
 *     For the same reason, changing an existing `author:` needs the CURRENT
 *     owner's approval.
 *   - `.claude-plugin/marketplace.json` stays with core. It is what ingest
 *     publishes, and removing an entry unpublishes the skill (`prune: true`).
 *
 * Usage:
 *   bun scripts/codeowners.ts --write          # regenerate the committed file
 *   bun scripts/codeowners.ts --check          # exit 1 when the committed file differs
 *   bun scripts/codeowners.ts --github-errors  # exit 1 when GitHub rejects a line (CI)
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { parseFrontmatter } from "./ingest.ts";

export const CODEOWNERS_PATH = ".github/CODEOWNERS";
export const REGENERATE_COMMAND = "bun scripts/codeowners.ts --write";
export const CORE_TEAM = "@devfellowship/core";
/** The org's own name as an author means "the team", not a person. */
export const ORG_AUTHOR = "devfellowship";

const HANDLE_RE = /^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$/;

/**
 * The GitHub owner an `author:` resolves to. `null` means core owns it.
 * Throws on a value that is neither absent nor a handle.
 */
export function ownerOf(author: string | undefined): string | null {
	if (author === undefined) return null;
	const handle = author.trim();
	if (!HANDLE_RE.test(handle)) {
		throw new Error(`author "${author}" is not a GitHub handle. Use your GitHub username, or ${ORG_AUTHOR} for the team.`);
	}
	return handle.toLowerCase() === ORG_AUTHOR ? null : `@${handle}`;
}

export function buildOwnership(root: string): { lines: string[]; errors: Array<{ file: string; message: string }> } {
	const errors: Array<{ file: string; message: string }> = [];
	const lines: string[] = [];
	const dir = join(root, "skills");
	const slugs = existsSync(dir)
		? readdirSync(dir)
				.filter((s) => statSync(join(dir, s)).isDirectory() && existsSync(join(dir, s, "SKILL.md")))
				.sort()
		: [];
	for (const slug of slugs) {
		const file = `skills/${slug}/SKILL.md`;
		try {
			const owner = ownerOf(parseFrontmatter(readFileSync(join(root, file), "utf8")).fm.author);
			if (owner) lines.push(`/skills/${slug}/ ${owner} ${CORE_TEAM}`);
		} catch (e) {
			errors.push({ file, message: (e as Error).message });
		}
	}
	return { lines, errors };
}

export function renderCodeowners(lines: string[]): string {
	return [
		"# GENERATED by scripts/codeowners.ts from the `author:` of every skill.",
		`# Do not edit by hand. Regenerate with: ${REGENERATE_COMMAND}`,
		"#",
		"# The owner of a skill must approve every change to it (or core must).",
		'# See README.md, "Dono e revisão".',
		"",
		`* ${CORE_TEAM}`,
		"",
		...lines,
		"",
	].join("\n");
}

/**
 * Ask GitHub which CODEOWNERS lines it rejects at `ref`. An owner without write
 * access is dropped silently, so a green `--check` alone does not prove the
 * named author can approve anything.
 */
async function githubErrors(): Promise<void> {
	const { GITHUB_TOKEN: token, REPO: repo, REF: ref } = process.env;
	if (!token || !repo || !ref) {
		console.error("--github-errors needs GITHUB_TOKEN, REPO and REF.");
		process.exit(2);
	}
	const res = await fetch(`https://api.github.com/repos/${repo}/codeowners/errors?ref=${encodeURIComponent(ref)}`, {
		headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" },
	});
	if (!res.ok) {
		console.error(`GitHub answered ${res.status} for the CODEOWNERS errors of ${repo}@${ref}.`);
		process.exit(1);
	}
	const { errors } = (await res.json()) as { errors: Array<{ line: number; kind: string; message: string }> };
	if (errors.length === 0) {
		console.log(`GitHub accepts every owner in ${CODEOWNERS_PATH} at ${ref}.`);
		return;
	}
	for (const e of errors) console.error(`OWNER-ERROR ${CODEOWNERS_PATH}:${e.line} (${e.kind}): ${e.message}`);
	console.error(
		"\nAn owner must be a GitHub user with write access to this repository. " +
			"Fix the author: that produced the line, or ask core to grant access.",
	);
	process.exit(1);
}

function main(): void {
	const mode = process.argv[2];
	if (mode === "--github-errors") {
		void githubErrors();
		return;
	}
	if (mode !== "--write" && mode !== "--check") {
		console.error("usage: bun scripts/codeowners.ts --write | --check | --github-errors");
		process.exit(2);
	}
	const root = process.cwd();
	const { lines, errors } = buildOwnership(root);
	if (errors.length > 0) {
		for (const e of errors) console.error(`OWNER-ERROR ${e.file}: ${e.message}`);
		process.exit(1);
	}
	const text = renderCodeowners(lines);

	const path = join(root, CODEOWNERS_PATH);
	if (mode === "--write") {
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, text);
		console.log(`wrote ${CODEOWNERS_PATH}: ${lines.length} owned path(s), the rest owned by ${CORE_TEAM}.`);
		return;
	}

	const committed = existsSync(path) ? readFileSync(path, "utf8") : null;
	if (committed === text) {
		console.log(`${CODEOWNERS_PATH} matches the generator output.`);
		return;
	}
	console.error(
		`CODEOWNERS DRIFT: ${CODEOWNERS_PATH} ${committed === null ? "is missing" : "differs from the generator output"}.\n` +
			`It is generated from the author: of every skill. Do not edit it by hand. Regenerate it and commit the result:\n\n` +
			`  ${REGENERATE_COMMAND}\n`,
	);
	process.exit(1);
}

if (import.meta.main) main();
